-- 코드를 입력하세요
SELECT a.CAR_ID, b.CAR_TYPE, round((100 - c.DISCOUNT_RATE)/100 * b.DAILY_FEE * 30) as FEE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY a
join CAR_RENTAL_COMPANY_CAR b
on a.CAR_ID =  b.CAR_ID
join CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
on b.CAR_TYPE = c.CAR_TYPE
where c.DURATION_TYPE = '30일 이상' and a.CAR_ID not in(
    select CAR_ID
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY
    where END_DATE >= '2022-11-01' and START_DATE <= '2022-11-30'
)
group by CAR_ID
having FEE >= 500000 and FEE < 2000000
order by FEE desc, CAR_ID;