-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) as YEAR, MONTH(o.SALES_DATE) as MONTH, u.GENDER, count(distinct u.USER_ID) as USERS
from ONLINE_SALE o
join USER_INFO u on o.USER_ID = u.USER_ID
where u.GENDER is not null
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER;
